import Head from "next/head";
import PropTypes from "prop-types";
import { Footer } from "src/components/Footer";
import { Header } from "src/components/Header";
import classes from "./Layout.module.css";

export const Layout = ({ children, title = "Create Next App" }) => {
  return (
    <div className={classes.container}>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      {children}
      <Footer />
    </div>
  );
};

Layout.propTypes = {
  children: PropTypes.node.isRequired,
  title: PropTypes.string,
};